export const ANIMATION_TYPES = [
  "cutting",
  "stirring",
  "waiting",
  "heating",
  "mixing",
  "pouring",
  "seasoning",
  "whisking",
  "kneading",
  "rolling",
  "grating",
  "peeling",
  "folding",
  "sauteing",
  "cooling",
  "blending",
  "steaming",
  "mashing",
  "straining",
  "measuring",
  "sifting",
  "beating",
  "crushing",
  "shredding",
  "juicing",
  "serving",
] as const;

export type AnimationType = (typeof ANIMATION_TYPES)[number];
